import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const teamMembers = [
  { name: 'Saniya Pawar', slug: 'saniya-pawar', role: 'President', category: 'Leadership', year: 'Session 2026-27', photoUrl: '/team/saniya-pawar.jpg', bio: 'President of the AIMSA council. Leads the student association of the AI & ML department with vision and keeps the community united and driven throughout the session.', highlightTag: 'PRESIDENT', displayOrder: 1 },
  { name: 'Ved Ringne', slug: 'ved-ringne', role: 'President', category: 'Leadership', year: 'Session 2026-27', photoUrl: '/team/ved-ringne.jpg', bio: 'President of the AIMSA council alongside the elected leadership team. Brings energy and direction to department initiatives, events, and student programs.', highlightTag: 'PRESIDENT', displayOrder: 2 },
  { name: 'Shrushtee Ghule', slug: 'shrushtee-ghule', role: 'Vice President', category: 'Leadership', year: 'Session 2026-27', photoUrl: '/team/shrushtee-ghule.jpg', bio: 'Vice President of AIMSA. Works closely with the council to coordinate planning, delegate responsibilities across the committee, and keep every wing aligned.', highlightTag: 'VICE PRESIDENT', displayOrder: 3 },
  { name: 'Vivek Singh', slug: 'vivek-singh', role: 'Vice President', category: 'Leadership', year: 'Session 2026-27', photoUrl: '/team/vivek-singh.jpg', bio: 'Vice President of AIMSA. Supports the presidents in council operations and helps bridge the gap between departments, students, and event execution teams.', highlightTag: 'VICE PRESIDENT', displayOrder: 4 },
  { name: 'Haresh Chavan', slug: 'haresh-chavan', role: 'Treasurer', category: 'Leadership', year: 'Session 2026-27', photoUrl: '/team/haresh-chavan.jpg', bio: 'Treasurer of AIMSA. Handles the association finances, budgets every event and fest, and keeps the money flows transparent and accountable to the council.', highlightTag: 'TREASURER', displayOrder: 5 },
  { name: 'Janhavi Chopkar', slug: 'janhavi-chopkar', role: 'Treasurer', category: 'Leadership', year: 'Session 2026-27', photoUrl: '/team/janhavi-chopkar.jpg', bio: 'Treasurer of AIMSA. Tracks expenses, coordinates with sponsors and vendors, and ensures every rupee allocated to events is used efficiently.', highlightTag: 'TREASURER', displayOrder: 6 },
  { name: 'Tanisha Pandey', slug: 'tanisha-pandey', role: 'Technical Secretary', category: 'Core Team', year: 'Session 2026-27', photoUrl: '/team/tanisha-pandey.jpg', bio: 'Technical Secretary of AIMSA. Drives the technical wing — workshops, hackathons, guest talks, and everything code-related in the AI & ML department.', highlightTag: 'TECHNICAL SECRETARY', displayOrder: 7 },
  { name: 'Rajkrishna Yadav', slug: 'rajkrishna-yadav', role: 'Co-Technical Secretary', category: 'Core Team', year: 'Session 2026-27', photoUrl: '/team/rajkrishna-yadav.jpg', bio: 'Co-Technical Secretary of AIMSA. Supports the technical wing in organizing hackathons, mentor sessions, and hands-on build events for the department.', highlightTag: 'CO-TECHNICAL SECRETARY', displayOrder: 8 },
  { name: 'Seema Karki', slug: 'seema-karki', role: 'Event Head', category: 'Core Team', year: 'Session 2026-27', photoUrl: '/team/seema-karki.jpg', bio: 'Event Head of AIMSA. Plans and runs the department events calendar — from technical fests to informal community gatherings across the AI & ML department.', highlightTag: 'EVENT HEAD', displayOrder: 9 },
  { name: 'Sahil Gouda', slug: 'sahil-gouda', role: 'Event Head', category: 'Core Team', year: 'Session 2026-27', photoUrl: '/team/sahil-gouda-event.jpg', bio: 'Event Head of AIMSA. Owns the end-to-end delivery of department events, from idea and logistics to on-ground execution with the volunteer crew.', highlightTag: 'EVENT HEAD', displayOrder: 10 },
  { name: 'Prasad Shetty', slug: 'prasad-shetty', role: 'Cultural Head', category: 'Core Team', year: 'Session 2026-27', photoUrl: '/team/prasad-shetty.jpg', bio: 'Cultural Head of AIMSA. Curates the cultural calendar — music nights, drama, and creative showcases that give the department its celebratory spirit.', highlightTag: 'CULTURAL HEAD', displayOrder: 11 },
  { name: 'Aneesh Chaurasia', slug: 'aneesh-chaurasia', role: 'Cultural Head', category: 'Core Team', year: 'Session 2026-27', photoUrl: '/team/aneesh-chaurasia.jpg', bio: 'Cultural Head of AIMSA. Co-leads the cultural wing, producing stage events and creative showcases for the AI & ML department community.', highlightTag: 'CULTURAL HEAD', displayOrder: 12 },
  { name: 'Swarangi Parab', slug: 'swarangi-parab', role: 'Creative Head', category: 'Department Leads', year: 'Session 2026-27', photoUrl: '/team/swarangi-parab.jpg', bio: 'Creative Head of AIMSA. Shapes the visual identity of the association — posters, branding, and social media creatives for every department event.', highlightTag: 'CREATIVE HEAD', displayOrder: 13 },
  { name: 'Vinay Kanojia', slug: 'vinay-kanojia', role: 'Photography & Magazine Head', category: 'Department Leads', year: 'Session 2026-27', photoUrl: '/team/vinay-kanojia.jpg', bio: 'Photography & Magazine Head of AIMSA. Captures the department in action and curates the association magazine, documenting student life and events.', highlightTag: 'PHOTOGRAPHY & MAGAZINE HEAD', displayOrder: 14 },
  { name: 'Om Shukla', slug: 'om-shukla', role: 'Photography & Magazine Head', category: 'Department Leads', year: 'Session 2026-27', photoUrl: '/team/om-shukla.jpg', bio: 'Photography & Magazine Head of AIMSA. Co-leads the media wing, shooting event highlights and compiling the stories that make up the association journal.', highlightTag: 'PHOTOGRAPHY & MAGAZINE HEAD', displayOrder: 15 },
  { name: 'Aditya Pandey', slug: 'aditya-pandey', role: 'Publicity Head', category: 'Department Leads', year: 'Session 2026-27', photoUrl: '/team/aditya-pandey.jpg', bio: 'Publicity Head of AIMSA. Spreads the word — managing announcements, social reach, and student engagement for every department activity.', highlightTag: 'PUBLICITY HEAD', displayOrder: 16 },
  { name: 'Aayush Pandey', slug: 'aayush-pandey', role: 'Sports Head', category: 'Department Leads', year: 'Session 2026-27', photoUrl: '/team/aayush-pandey.jpg', bio: 'Sports Head of AIMSA. Organizes the inter-department tournaments and league fixtures that bring the athletic spirit of the AIMSA community alive.', highlightTag: 'SPORTS HEAD', displayOrder: 17 },
  { name: 'Soham Patil', slug: 'soham-patil', role: 'Sports Head', category: 'Department Leads', year: 'Session 2026-27', photoUrl: '/team/soham-patil.jpg', bio: 'Sports Head of AIMSA. Co-leads the sports wing, organizing matches, training schedules, and the competitive calendar for the department.', highlightTag: 'SPORTS HEAD', displayOrder: 18 },
  { name: 'Pranav Badgujar', slug: 'pranav-badgujar', role: 'Sports Event Head', category: 'Department Leads', year: 'Session 2026-27', photoUrl: '/team/pranav-badgujar.jpg', bio: 'Sports Event Head of AIMSA. Leads ground execution of sports events — bookings, referees, scoring, and crowd coordination during tournaments.', highlightTag: 'SPORTS EVENT HEAD', displayOrder: 19 },
  { name: 'Anannya Bangera', slug: 'anannya-bangera', role: 'Sports Event Head', category: 'Department Leads', year: 'Session 2026-27', photoUrl: '/team/anannya-bangera.jpg', bio: 'Sports Event Head of AIMSA. Delivers the sports day operations — from event scheduling to making sure every match runs smoothly on the field.', highlightTag: 'SPORTS EVENT HEAD', displayOrder: 20 },
  { name: 'Adi Shenoy', slug: 'adi-shenoy', role: 'Team Member', category: 'Executive Committee', year: 'Session 2026-27', photoUrl: '/team/adi-shenoy.jpg', bio: 'Executive committee member of AIMSA. Contributes to event execution and keeps the department community involved throughout the session.', highlightTag: 'TEAM MEMBER', displayOrder: 21 },
  { name: 'Shreya Yadav', slug: 'shreya-yadav', role: 'Team Member', category: 'Executive Committee', year: 'Session 2026-27', photoUrl: '/team/shreya-yadav.jpg', bio: 'Executive committee member of AIMSA. Brings enthusiasm to community events and supports the committee across the department calendar.', highlightTag: 'TEAM MEMBER', displayOrder: 22 },
  { name: 'Tanushree Lokare', slug: 'tanushree-lokare', role: 'Team Member', category: 'Executive Committee', year: 'Session 2026-27', photoUrl: '/team/tanushree-lokare.jpg', bio: 'Executive committee member of AIMSA. Lends a hand across technical and cultural events and helps grow the AI & ML department community.', highlightTag: 'TEAM MEMBER', displayOrder: 23 },
  { name: 'Srushti Shinde', slug: 'srushti-shinde', role: 'Team Member', category: 'Executive Committee', year: 'Session 2026-27', photoUrl: '/team/srushti-shinde.jpg', bio: 'Executive committee member of AIMSA. Helps run departmental activities and makes sure no student feels left out of the AIMSA community.', highlightTag: 'TEAM MEMBER', displayOrder: 24 },
  { name: 'Shreya Tripathi', slug: 'shreya-tripathi', role: 'Team Member', category: 'Executive Committee', year: 'Session 2026-27', photoUrl: '/team/shreya-tripathi.jpg', bio: 'Executive committee member of AIMSA. Contributes to event planning and supports the committee crew during department fests and gatherings.', highlightTag: 'TEAM MEMBER', displayOrder: 25 },
  { name: 'Parnika Walunj', slug: 'parnika-walunj', role: 'Team Member', category: 'Executive Committee', year: 'Session 2026-27', photoUrl: '/team/parnika-walunj.jpg', bio: 'Executive committee member of AIMSA. Brings dedication to the volunteer teams and helps keep department events and initiatives running smoothly.', highlightTag: 'TEAM MEMBER', displayOrder: 26 },
  { name: 'Soham Mahajan', slug: 'soham-mahajan', role: 'Team Member', category: 'Executive Committee', year: 'Session 2026-27', photoUrl: '/team/soham-mahajan.jpg', bio: 'Executive committee member of AIMSA. Helps with the behind-the-scenes work that makes department events and gatherings feel effortless.', highlightTag: 'TEAM MEMBER', displayOrder: 27 },
  { name: 'Zaid Mohd', slug: 'zaid-mohd', role: 'Team Member', category: 'Executive Committee', year: 'Session 2026-27', photoUrl: '/team/zaid-mohd.jpg', bio: 'Executive committee member of AIMSA. Contributes to the council teams and helps keep the AI & ML department community active and welcoming.', highlightTag: 'TEAM MEMBER', displayOrder: 28 },
];

async function seedTeam() {
  console.log('Seeding team members...');
  
  for (const member of teamMembers) {
    await prisma.teamMember.upsert({
      where: { slug: member.slug },
      update: {},
      create: member,
    });
  }
  
  console.log(`  ${teamMembers.length} team members seeded`);
}

seedTeam()
  .catch(console.error)
  .finally(() => prisma.$disconnect());
