import type { ResourceConfig } from "@/components/admin/ResourceManager";

const opts = (values: string[]) => values.map((v) => ({ label: v, value: v }));

export const eventsResource: ResourceConfig = {
  table: "events",
  title: "Events",
  description:
    "Create, schedule and publish AIMSA events. Published events appear on the public events page immediately.",
  singular: "Event",
  labelField: "title",
  searchFields: ["title", "summary", "venue"],
  hasStatus: true,
  orderBy: { column: "start_date", ascending: false },
  fields: [
    { name: "title", label: "Title", type: "text", required: true, column: true },
    {
      name: "slug",
      label: "Slug",
      type: "text",
      required: true,
      column: true,
      help: "URL segment, e.g. aimsa-tech-debate-2026",
    },
    { name: "summary", label: "Summary", type: "textarea", required: true },
    { name: "description", label: "Full description", type: "richtext", required: true, help: "One paragraph per line." },
    {
      name: "category",
      label: "Category",
      type: "select",
      column: true,
      defaultValue: "Workshop",
      options: opts(["Workshop", "Debate", "Hackathon", "Seminar", "Bootcamp", "Competition", "Community"]),
    },
    { name: "format", label: "Format", type: "select", defaultValue: "In-person", options: opts(["In-person", "Online", "Hybrid"]) },
    {
      name: "state",
      label: "Lifecycle",
      type: "select",
      defaultValue: "upcoming",
      options: opts(["upcoming", "ongoing", "past", "cancelled"]),
    },
    { name: "start_date", label: "Starts", type: "datetime", column: true },
    { name: "end_date", label: "Ends", type: "datetime" },
    { name: "venue", label: "Venue", type: "text" },
    { name: "registration_deadline", label: "Registration deadline", type: "datetime" },
    { name: "registration_url", label: "Registration link", type: "url" },
    { name: "publish_at", label: "Scheduled publish date", type: "datetime", help: "Optional. Leave empty to publish immediately." },
    { name: "poster_url", label: "Poster", type: "image" },
    { name: "banner_url", label: "Banner", type: "image" },
    { name: "eligibility", label: "Eligibility", type: "tags", help: "Comma separated." },
    { name: "organizers", label: "Organisers", type: "tags" },
    { name: "rules", label: "Rules", type: "tags" },
    { name: "featured", label: "Feature on home page", type: "boolean" },
  ],
};

export const announcementsResource: ResourceConfig = {
  table: "announcements",
  title: "Announcements",
  description: "Notices shown on the announcement board and the site-wide banner.",
  singular: "Announcement",
  labelField: "title",
  searchFields: ["title", "summary"],
  hasStatus: true,
  orderBy: { column: "publish_at", ascending: false },
  fields: [
    { name: "title", label: "Title", type: "text", required: true, column: true },
    { name: "summary", label: "Summary", type: "textarea", required: true },
    { name: "body", label: "Full text", type: "richtext", required: true, help: "One paragraph per line." },
    {
      name: "category",
      label: "Category",
      type: "select",
      column: true,
      defaultValue: "Notice",
      options: opts(["Registration", "Notice", "Result", "Update"]),
    },
    { name: "publish_at", label: "Publish date", type: "datetime", column: true },
    { name: "expires_at", label: "Expires", type: "datetime" },
    { name: "pinned", label: "Pin to top", type: "boolean", column: true },
    { name: "image_url", label: "Image", type: "image" },
    { name: "cta_label", label: "Button label", type: "text" },
    { name: "cta_href", label: "Button link", type: "text" },
  ],
};

export const teamResource: ResourceConfig = {
  table: "team_members",
  title: "Team members",
  description: "Faculty coordinators, office bearers and functional teams.",
  singular: "Team member",
  labelField: "name",
  searchFields: ["name", "position"],
  hasStatus: true,
  orderBy: { column: "sort_order", ascending: true },
  fields: [
    { name: "name", label: "Name", type: "text", required: true, column: true },
    { name: "position", label: "Position", type: "text", required: true, column: true },
    {
      name: "group_name",
      label: "Group",
      type: "select",
      column: true,
      defaultValue: "Office Bearers",
      options: opts(["Faculty", "Office Bearers", "Technical", "Events", "Design & Media"]),
    },
    { name: "academic_year", label: "Academic year", type: "text", placeholder: "2025-26" },
    { name: "department", label: "Department", type: "text" },
    { name: "bio", label: "Short bio", type: "textarea" },
    { name: "photo_url", label: "Photo", type: "image" },
    { name: "email", label: "Email", type: "text" },
    { name: "linkedin", label: "LinkedIn URL", type: "url" },
    { name: "github", label: "GitHub URL", type: "url" },
    { name: "sort_order", label: "Display order", type: "number", defaultValue: 0 },
    { name: "active", label: "Currently serving", type: "boolean", defaultValue: true },
  ],
};

export const projectsResource: ResourceConfig = {
  table: "projects",
  title: "Projects",
  description: "Student build showcase entries.",
  singular: "Project",
  labelField: "title",
  searchFields: ["title", "summary", "domain"],
  hasStatus: true,
  fields: [
    { name: "title", label: "Title", type: "text", required: true, column: true },
    { name: "summary", label: "Summary", type: "textarea", required: true },
    { name: "description", label: "Full description", type: "richtext" },
    {
      name: "domain",
      label: "Domain",
      type: "select",
      column: true,
      defaultValue: "Machine Learning",
      options: opts(["Machine Learning", "Computer Vision", "NLP", "Data Science", "Generative AI", "Robotics", "Tooling"]),
    },
    {
      name: "stage",
      label: "Stage",
      type: "select",
      column: true,
      defaultValue: "Concept",
      options: opts(["Concept", "In development", "Shipped"]),
    },
    { name: "year", label: "Year", type: "text", column: true },
    { name: "stack", label: "Tech stack", type: "tags" },
    { name: "builders", label: "Builders", type: "tags" },
    { name: "repo_url", label: "Repository", type: "url" },
    { name: "demo_url", label: "Live demo", type: "url" },
    { name: "writeup_url", label: "Write-up", type: "url" },
    { name: "image_url", label: "Cover image", type: "image" },
    { name: "featured", label: "Feature on home page", type: "boolean" },
  ],
};

export const achievementsResource: ResourceConfig = {
  table: "achievements",
  title: "Achievements",
  description: "Verified records only — every entry should link to supporting evidence.",
  singular: "Achievement",
  labelField: "title",
  searchFields: ["title", "category", "competition"],
  hasStatus: true,
  fields: [
    { name: "title", label: "Title", type: "text", required: true, column: true },
    { name: "category", label: "Category", type: "text", required: true, column: true, defaultValue: "Competition" },
    { name: "year", label: "Year", type: "text", column: true },
    { name: "achieved_on", label: "Date achieved", type: "date" },
    { name: "competition", label: "Competition / context", type: "text" },
    { name: "position", label: "Position / result", type: "text", column: true },
    { name: "description", label: "Description", type: "textarea", required: true },
    { name: "participants", label: "Contributors", type: "tags" },
    { name: "evidence_url", label: "Evidence link", type: "url" },
    { name: "image_url", label: "Image", type: "image" },
  ],
};

export const galleryResource: ResourceConfig = {
  table: "gallery_albums",
  title: "Gallery albums",
  description: "Photo albums grouped by event or year. Manage the photos inside an album from the gallery page.",
  singular: "Album",
  labelField: "title",
  searchFields: ["title", "category"],
  hasStatus: true,
  orderBy: { column: "sort_order", ascending: true },
  fields: [
    { name: "title", label: "Album title", type: "text", required: true, column: true },
    { name: "year", label: "Year", type: "text", column: true },
    { name: "category", label: "Category", type: "text", column: true, defaultValue: "Events" },
    { name: "cover_url", label: "Cover image", type: "image" },
    { name: "description", label: "Description", type: "textarea" },
    { name: "sort_order", label: "Display order", type: "number", defaultValue: 0 },
  ],
};
